require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - 'assets/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可
Style/Documentation:
  Enabled: false

# frozen_string_literal の指定強制を解除
Style/FrozenStringLiteralComment:
  Enabled: false

# 1行の最大
Layout/LineLength:
  Max: 160

# 文字列はダブルクォートに統一
Style/StringLiterals:
  EnforcedStyle: double_quotes

# %w, %i を使用強制を解除
Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# プロック内の行数を除外
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/forms/*'

# デフォルト値をnested形式からcompact形式に変更
ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/application_cable/*'
    - 'config/*'

# deviseのアクションのため除外
Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/*'

# seedファイルの正常確認のため除外
Rails/Output:
  Exclude:
    - 'db/seeds.rb'
